version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:Shuggie0907!@localhost:5432/triswiftdb
      - JWT_SECRET=fastsecret123
    volumes:
      - ./backend:/usr/src/app
    restart: always

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Shuggie0907!
      POSTGRES_DB: triswiftdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
